### PR TITLE
v3.0.0

### PR DESCRIPTION
**Pull request by gilbox**
@ljharb

### CODE REVIEW

**Comment by gilbox** [comment]
@ljharb I don't have permissions to do that

**Comment by ljharb** [comment]
@gilbox since you have permission to merge the PR, and the PR is approved, if you push the commit directly to master (with the same SHA), it will go through, and github will detect it and auto-mark the PR as merged.

**Comment by gilbox** [comment]
ah, ty!

**Comment by ljharb** [comment]
(Then you can tag the commit, push up the tag, and once tests pass on master and/or the tag, `npm publish`)

**Pull request merged**
